// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

'use strict'

const assert = require('assert')

function ESAPI (opts) {
  assert(opts.makeRequest, 'Missing makeRequest function')
  assert(opts.ConfigurationError, 'Missing ConfigurationError class')
  assert(opts.result, 'Missing default result object')

  const { result } = opts
  opts.handleError = handleError
  opts.snakeCaseKeys = snakeCaseKeys

  const apis = {
    async_search: {
      delete: require('./api/async_search.delete.js')(opts),
      get: require('./api/async_search.get.js')(opts),
      submit: require('./api/async_search.submit.js')(opts)
    },
    asyncSearch: {
      delete: require('./api/async_search.delete.js')(opts),
      get: require('./api/async_search.get.js')(opts),
      submit: require('./api/async_search.submit.js')(opts)
    },
    autoscaling: {
      get_autoscaling_decision: require('./api/autoscaling.get_autoscaling_decision.js')(opts),
      getAutoscalingDecision: require('./api/autoscaling.get_autoscaling_decision.js')(opts)
    },
    bulk: require('./api/bulk.js')(opts),
    cat: {
      aliases: require('./api/cat.aliases.js')(opts),
      allocation: require('./api/cat.allocation.js')(opts),
      count: require('./api/cat.count.js')(opts),
      fielddata: require('./api/cat.fielddata.js')(opts),
      health: require('./api/cat.health.js')(opts),
      help: require('./api/cat.help.js')(opts),
      indices: require('./api/cat.indices.js')(opts),
      master: require('./api/cat.master.js')(opts),
      ml_data_frame_analytics: require('./api/cat.ml_data_frame_analytics.js')(opts),
      mlDataFrameAnalytics: require('./api/cat.ml_data_frame_analytics.js')(opts),
      ml_datafeeds: require('./api/cat.ml_datafeeds.js')(opts),
      mlDatafeeds: require('./api/cat.ml_datafeeds.js')(opts),
      ml_jobs: require('./api/cat.ml_jobs.js')(opts),
      mlJobs: require('./api/cat.ml_jobs.js')(opts),
      ml_trained_models: require('./api/cat.ml_trained_models.js')(opts),
      mlTrainedModels: require('./api/cat.ml_trained_models.js')(opts),
      nodeattrs: require('./api/cat.nodeattrs.js')(opts),
      nodes: require('./api/cat.nodes.js')(opts),
      pending_tasks: require('./api/cat.pending_tasks.js')(opts),
      pendingTasks: require('./api/cat.pending_tasks.js')(opts),
      plugins: require('./api/cat.plugins.js')(opts),
      recovery: require('./api/cat.recovery.js')(opts),
      repositories: require('./api/cat.repositories.js')(opts),
      segments: require('./api/cat.segments.js')(opts),
      shards: require('./api/cat.shards.js')(opts),
      snapshots: require('./api/cat.snapshots.js')(opts),
      tasks: require('./api/cat.tasks.js')(opts),
      templates: require('./api/cat.templates.js')(opts),
      thread_pool: require('./api/cat.thread_pool.js')(opts),
      threadPool: require('./api/cat.thread_pool.js')(opts),
      transform: require('./api/cat.transform.js')(opts)
    },
    ccr: {
      delete_auto_follow_pattern: require('./api/ccr.delete_auto_follow_pattern.js')(opts),
      deleteAutoFollowPattern: require('./api/ccr.delete_auto_follow_pattern.js')(opts),
      follow: require('./api/ccr.follow.js')(opts),
      follow_info: require('./api/ccr.follow_info.js')(opts),
      followInfo: require('./api/ccr.follow_info.js')(opts),
      follow_stats: require('./api/ccr.follow_stats.js')(opts),
      followStats: require('./api/ccr.follow_stats.js')(opts),
      forget_follower: require('./api/ccr.forget_follower.js')(opts),
      forgetFollower: require('./api/ccr.forget_follower.js')(opts),
      get_auto_follow_pattern: require('./api/ccr.get_auto_follow_pattern.js')(opts),
      getAutoFollowPattern: require('./api/ccr.get_auto_follow_pattern.js')(opts),
      pause_auto_follow_pattern: require('./api/ccr.pause_auto_follow_pattern.js')(opts),
      pauseAutoFollowPattern: require('./api/ccr.pause_auto_follow_pattern.js')(opts),
      pause_follow: require('./api/ccr.pause_follow.js')(opts),
      pauseFollow: require('./api/ccr.pause_follow.js')(opts),
      put_auto_follow_pattern: require('./api/ccr.put_auto_follow_pattern.js')(opts),
      putAutoFollowPattern: require('./api/ccr.put_auto_follow_pattern.js')(opts),
      resume_auto_follow_pattern: require('./api/ccr.resume_auto_follow_pattern.js')(opts),
      resumeAutoFollowPattern: require('./api/ccr.resume_auto_follow_pattern.js')(opts),
      resume_follow: require('./api/ccr.resume_follow.js')(opts),
      resumeFollow: require('./api/ccr.resume_follow.js')(opts),
      stats: require('./api/ccr.stats.js')(opts),
      unfollow: require('./api/ccr.unfollow.js')(opts)
    },
    clear_scroll: require('./api/clear_scroll.js')(opts),
    clearScroll: require('./api/clear_scroll.js')(opts),
    cluster: {
      allocation_explain: require('./api/cluster.allocation_explain.js')(opts),
      allocationExplain: require('./api/cluster.allocation_explain.js')(opts),
      delete_component_template: require('./api/cluster.delete_component_template.js')(opts),
      deleteComponentTemplate: require('./api/cluster.delete_component_template.js')(opts),
      get_component_template: require('./api/cluster.get_component_template.js')(opts),
      getComponentTemplate: require('./api/cluster.get_component_template.js')(opts),
      get_settings: require('./api/cluster.get_settings.js')(opts),
      getSettings: require('./api/cluster.get_settings.js')(opts),
      health: require('./api/cluster.health.js')(opts),
      pending_tasks: require('./api/cluster.pending_tasks.js')(opts),
      pendingTasks: require('./api/cluster.pending_tasks.js')(opts),
      put_component_template: require('./api/cluster.put_component_template.js')(opts),
      putComponentTemplate: require('./api/cluster.put_component_template.js')(opts),
      put_settings: require('./api/cluster.put_settings.js')(opts),
      putSettings: require('./api/cluster.put_settings.js')(opts),
      remote_info: require('./api/cluster.remote_info.js')(opts),
      remoteInfo: require('./api/cluster.remote_info.js')(opts),
      reroute: require('./api/cluster.reroute.js')(opts),
      state: require('./api/cluster.state.js')(opts),
      stats: require('./api/cluster.stats.js')(opts)
    },
    count: require('./api/count.js')(opts),
    create: require('./api/create.js')(opts),
    data_frame_transform_deprecated: {
      delete_transform: require('./api/data_frame_transform_deprecated.delete_transform.js')(opts),
      deleteTransform: require('./api/data_frame_transform_deprecated.delete_transform.js')(opts),
      get_transform: require('./api/data_frame_transform_deprecated.get_transform.js')(opts),
      getTransform: require('./api/data_frame_transform_deprecated.get_transform.js')(opts),
      get_transform_stats: require('./api/data_frame_transform_deprecated.get_transform_stats.js')(opts),
      getTransformStats: require('./api/data_frame_transform_deprecated.get_transform_stats.js')(opts),
      preview_transform: require('./api/data_frame_transform_deprecated.preview_transform.js')(opts),
      previewTransform: require('./api/data_frame_transform_deprecated.preview_transform.js')(opts),
      put_transform: require('./api/data_frame_transform_deprecated.put_transform.js')(opts),
      putTransform: require('./api/data_frame_transform_deprecated.put_transform.js')(opts),
      start_transform: require('./api/data_frame_transform_deprecated.start_transform.js')(opts),
      startTransform: require('./api/data_frame_transform_deprecated.start_transform.js')(opts),
      stop_transform: require('./api/data_frame_transform_deprecated.stop_transform.js')(opts),
      stopTransform: require('./api/data_frame_transform_deprecated.stop_transform.js')(opts),
      update_transform: require('./api/data_frame_transform_deprecated.update_transform.js')(opts),
      updateTransform: require('./api/data_frame_transform_deprecated.update_transform.js')(opts)
    },
    dataFrameTransformDeprecated: {
      delete_transform: require('./api/data_frame_transform_deprecated.delete_transform.js')(opts),
      deleteTransform: require('./api/data_frame_transform_deprecated.delete_transform.js')(opts),
      get_transform: require('./api/data_frame_transform_deprecated.get_transform.js')(opts),
      getTransform: require('./api/data_frame_transform_deprecated.get_transform.js')(opts),
      get_transform_stats: require('./api/data_frame_transform_deprecated.get_transform_stats.js')(opts),
      getTransformStats: require('./api/data_frame_transform_deprecated.get_transform_stats.js')(opts),
      preview_transform: require('./api/data_frame_transform_deprecated.preview_transform.js')(opts),
      previewTransform: require('./api/data_frame_transform_deprecated.preview_transform.js')(opts),
      put_transform: require('./api/data_frame_transform_deprecated.put_transform.js')(opts),
      putTransform: require('./api/data_frame_transform_deprecated.put_transform.js')(opts),
      start_transform: require('./api/data_frame_transform_deprecated.start_transform.js')(opts),
      startTransform: require('./api/data_frame_transform_deprecated.start_transform.js')(opts),
      stop_transform: require('./api/data_frame_transform_deprecated.stop_transform.js')(opts),
      stopTransform: require('./api/data_frame_transform_deprecated.stop_transform.js')(opts),
      update_transform: require('./api/data_frame_transform_deprecated.update_transform.js')(opts),
      updateTransform: require('./api/data_frame_transform_deprecated.update_transform.js')(opts)
    },
    delete: require('./api/delete.js')(opts),
    delete_by_query: require('./api/delete_by_query.js')(opts),
    deleteByQuery: require('./api/delete_by_query.js')(opts),
    delete_by_query_rethrottle: require('./api/delete_by_query_rethrottle.js')(opts),
    deleteByQueryRethrottle: require('./api/delete_by_query_rethrottle.js')(opts),
    delete_script: require('./api/delete_script.js')(opts),
    deleteScript: require('./api/delete_script.js')(opts),
    enrich: {
      delete_policy: require('./api/enrich.delete_policy.js')(opts),
      deletePolicy: require('./api/enrich.delete_policy.js')(opts),
      execute_policy: require('./api/enrich.execute_policy.js')(opts),
      executePolicy: require('./api/enrich.execute_policy.js')(opts),
      get_policy: require('./api/enrich.get_policy.js')(opts),
      getPolicy: require('./api/enrich.get_policy.js')(opts),
      put_policy: require('./api/enrich.put_policy.js')(opts),
      putPolicy: require('./api/enrich.put_policy.js')(opts),
      stats: require('./api/enrich.stats.js')(opts)
    },
    eql: {
      search: require('./api/eql.search.js')(opts)
    },
    exists: require('./api/exists.js')(opts),
    exists_source: require('./api/exists_source.js')(opts),
    existsSource: require('./api/exists_source.js')(opts),
    explain: require('./api/explain.js')(opts),
    field_caps: require('./api/field_caps.js')(opts),
    fieldCaps: require('./api/field_caps.js')(opts),
    get: require('./api/get.js')(opts),
    get_script: require('./api/get_script.js')(opts),
    getScript: require('./api/get_script.js')(opts),
    get_script_context: require('./api/get_script_context.js')(opts),
    getScriptContext: require('./api/get_script_context.js')(opts),
    get_script_languages: require('./api/get_script_languages.js')(opts),
    getScriptLanguages: require('./api/get_script_languages.js')(opts),
    get_source: require('./api/get_source.js')(opts),
    getSource: require('./api/get_source.js')(opts),
    graph: {
      explore: require('./api/graph.explore.js')(opts)
    },
    ilm: {
      delete_lifecycle: require('./api/ilm.delete_lifecycle.js')(opts),
      deleteLifecycle: require('./api/ilm.delete_lifecycle.js')(opts),
      explain_lifecycle: require('./api/ilm.explain_lifecycle.js')(opts),
      explainLifecycle: require('./api/ilm.explain_lifecycle.js')(opts),
      get_lifecycle: require('./api/ilm.get_lifecycle.js')(opts),
      getLifecycle: require('./api/ilm.get_lifecycle.js')(opts),
      get_status: require('./api/ilm.get_status.js')(opts),
      getStatus: require('./api/ilm.get_status.js')(opts),
      move_to_step: require('./api/ilm.move_to_step.js')(opts),
      moveToStep: require('./api/ilm.move_to_step.js')(opts),
      put_lifecycle: require('./api/ilm.put_lifecycle.js')(opts),
      putLifecycle: require('./api/ilm.put_lifecycle.js')(opts),
      remove_policy: require('./api/ilm.remove_policy.js')(opts),
      removePolicy: require('./api/ilm.remove_policy.js')(opts),
      retry: require('./api/ilm.retry.js')(opts),
      start: require('./api/ilm.start.js')(opts),
      stop: require('./api/ilm.stop.js')(opts)
    },
    index: require('./api/index.js')(opts),
    indices: {
      analyze: require('./api/indices.analyze.js')(opts),
      clear_cache: require('./api/indices.clear_cache.js')(opts),
      clearCache: require('./api/indices.clear_cache.js')(opts),
      clone: require('./api/indices.clone.js')(opts),
      close: require('./api/indices.close.js')(opts),
      create: require('./api/indices.create.js')(opts),
      create_data_stream: require('./api/indices.create_data_stream.js')(opts),
      createDataStream: require('./api/indices.create_data_stream.js')(opts),
      delete: require('./api/indices.delete.js')(opts),
      delete_alias: require('./api/indices.delete_alias.js')(opts),
      deleteAlias: require('./api/indices.delete_alias.js')(opts),
      delete_data_stream: require('./api/indices.delete_data_stream.js')(opts),
      deleteDataStream: require('./api/indices.delete_data_stream.js')(opts),
      delete_template: require('./api/indices.delete_template.js')(opts),
      deleteTemplate: require('./api/indices.delete_template.js')(opts),
      exists: require('./api/indices.exists.js')(opts),
      exists_alias: require('./api/indices.exists_alias.js')(opts),
      existsAlias: require('./api/indices.exists_alias.js')(opts),
      exists_template: require('./api/indices.exists_template.js')(opts),
      existsTemplate: require('./api/indices.exists_template.js')(opts),
      exists_type: require('./api/indices.exists_type.js')(opts),
      existsType: require('./api/indices.exists_type.js')(opts),
      flush: require('./api/indices.flush.js')(opts),
      forcemerge: require('./api/indices.forcemerge.js')(opts),
      freeze: require('./api/indices.freeze.js')(opts),
      get: require('./api/indices.get.js')(opts),
      get_alias: require('./api/indices.get_alias.js')(opts),
      getAlias: require('./api/indices.get_alias.js')(opts),
      get_data_streams: require('./api/indices.get_data_streams.js')(opts),
      getDataStreams: require('./api/indices.get_data_streams.js')(opts),
      get_field_mapping: require('./api/indices.get_field_mapping.js')(opts),
      getFieldMapping: require('./api/indices.get_field_mapping.js')(opts),
      get_mapping: require('./api/indices.get_mapping.js')(opts),
      getMapping: require('./api/indices.get_mapping.js')(opts),
      get_settings: require('./api/indices.get_settings.js')(opts),
      getSettings: require('./api/indices.get_settings.js')(opts),
      get_template: require('./api/indices.get_template.js')(opts),
      getTemplate: require('./api/indices.get_template.js')(opts),
      get_upgrade: require('./api/indices.get_upgrade.js')(opts),
      getUpgrade: require('./api/indices.get_upgrade.js')(opts),
      open: require('./api/indices.open.js')(opts),
      put_alias: require('./api/indices.put_alias.js')(opts),
      putAlias: require('./api/indices.put_alias.js')(opts),
      put_mapping: require('./api/indices.put_mapping.js')(opts),
      putMapping: require('./api/indices.put_mapping.js')(opts),
      put_settings: require('./api/indices.put_settings.js')(opts),
      putSettings: require('./api/indices.put_settings.js')(opts),
      put_template: require('./api/indices.put_template.js')(opts),
      putTemplate: require('./api/indices.put_template.js')(opts),
      recovery: require('./api/indices.recovery.js')(opts),
      refresh: require('./api/indices.refresh.js')(opts),
      reload_search_analyzers: require('./api/indices.reload_search_analyzers.js')(opts),
      reloadSearchAnalyzers: require('./api/indices.reload_search_analyzers.js')(opts),
      rollover: require('./api/indices.rollover.js')(opts),
      segments: require('./api/indices.segments.js')(opts),
      shard_stores: require('./api/indices.shard_stores.js')(opts),
      shardStores: require('./api/indices.shard_stores.js')(opts),
      shrink: require('./api/indices.shrink.js')(opts),
      split: require('./api/indices.split.js')(opts),
      stats: require('./api/indices.stats.js')(opts),
      unfreeze: require('./api/indices.unfreeze.js')(opts),
      update_aliases: require('./api/indices.update_aliases.js')(opts),
      updateAliases: require('./api/indices.update_aliases.js')(opts),
      upgrade: require('./api/indices.upgrade.js')(opts),
      validate_query: require('./api/indices.validate_query.js')(opts),
      validateQuery: require('./api/indices.validate_query.js')(opts)
    },
    info: require('./api/info.js')(opts),
    ingest: {
      delete_pipeline: require('./api/ingest.delete_pipeline.js')(opts),
      deletePipeline: require('./api/ingest.delete_pipeline.js')(opts),
      get_pipeline: require('./api/ingest.get_pipeline.js')(opts),
      getPipeline: require('./api/ingest.get_pipeline.js')(opts),
      processor_grok: require('./api/ingest.processor_grok.js')(opts),
      processorGrok: require('./api/ingest.processor_grok.js')(opts),
      put_pipeline: require('./api/ingest.put_pipeline.js')(opts),
      putPipeline: require('./api/ingest.put_pipeline.js')(opts),
      simulate: require('./api/ingest.simulate.js')(opts)
    },
    license: {
      delete: require('./api/license.delete.js')(opts),
      get: require('./api/license.get.js')(opts),
      get_basic_status: require('./api/license.get_basic_status.js')(opts),
      getBasicStatus: require('./api/license.get_basic_status.js')(opts),
      get_trial_status: require('./api/license.get_trial_status.js')(opts),
      getTrialStatus: require('./api/license.get_trial_status.js')(opts),
      post: require('./api/license.post.js')(opts),
      post_start_basic: require('./api/license.post_start_basic.js')(opts),
      postStartBasic: require('./api/license.post_start_basic.js')(opts),
      post_start_trial: require('./api/license.post_start_trial.js')(opts),
      postStartTrial: require('./api/license.post_start_trial.js')(opts)
    },
    mget: require('./api/mget.js')(opts),
    migration: {
      deprecations: require('./api/migration.deprecations.js')(opts)
    },
    ml: {
      close_job: require('./api/ml.close_job.js')(opts),
      closeJob: require('./api/ml.close_job.js')(opts),
      delete_calendar: require('./api/ml.delete_calendar.js')(opts),
      deleteCalendar: require('./api/ml.delete_calendar.js')(opts),
      delete_calendar_event: require('./api/ml.delete_calendar_event.js')(opts),
      deleteCalendarEvent: require('./api/ml.delete_calendar_event.js')(opts),
      delete_calendar_job: require('./api/ml.delete_calendar_job.js')(opts),
      deleteCalendarJob: require('./api/ml.delete_calendar_job.js')(opts),
      delete_data_frame_analytics: require('./api/ml.delete_data_frame_analytics.js')(opts),
      deleteDataFrameAnalytics: require('./api/ml.delete_data_frame_analytics.js')(opts),
      delete_datafeed: require('./api/ml.delete_datafeed.js')(opts),
      deleteDatafeed: require('./api/ml.delete_datafeed.js')(opts),
      delete_expired_data: require('./api/ml.delete_expired_data.js')(opts),
      deleteExpiredData: require('./api/ml.delete_expired_data.js')(opts),
      delete_filter: require('./api/ml.delete_filter.js')(opts),
      deleteFilter: require('./api/ml.delete_filter.js')(opts),
      delete_forecast: require('./api/ml.delete_forecast.js')(opts),
      deleteForecast: require('./api/ml.delete_forecast.js')(opts),
      delete_job: require('./api/ml.delete_job.js')(opts),
      deleteJob: require('./api/ml.delete_job.js')(opts),
      delete_model_snapshot: require('./api/ml.delete_model_snapshot.js')(opts),
      deleteModelSnapshot: require('./api/ml.delete_model_snapshot.js')(opts),
      delete_trained_model: require('./api/ml.delete_trained_model.js')(opts),
      deleteTrainedModel: require('./api/ml.delete_trained_model.js')(opts),
      estimate_model_memory: require('./api/ml.estimate_model_memory.js')(opts),
      estimateModelMemory: require('./api/ml.estimate_model_memory.js')(opts),
      evaluate_data_frame: require('./api/ml.evaluate_data_frame.js')(opts),
      evaluateDataFrame: require('./api/ml.evaluate_data_frame.js')(opts),
      explain_data_frame_analytics: require('./api/ml.explain_data_frame_analytics.js')(opts),
      explainDataFrameAnalytics: require('./api/ml.explain_data_frame_analytics.js')(opts),
      find_file_structure: require('./api/ml.find_file_structure.js')(opts),
      findFileStructure: require('./api/ml.find_file_structure.js')(opts),
      flush_job: require('./api/ml.flush_job.js')(opts),
      flushJob: require('./api/ml.flush_job.js')(opts),
      forecast: require('./api/ml.forecast.js')(opts),
      get_buckets: require('./api/ml.get_buckets.js')(opts),
      getBuckets: require('./api/ml.get_buckets.js')(opts),
      get_calendar_events: require('./api/ml.get_calendar_events.js')(opts),
      getCalendarEvents: require('./api/ml.get_calendar_events.js')(opts),
      get_calendars: require('./api/ml.get_calendars.js')(opts),
      getCalendars: require('./api/ml.get_calendars.js')(opts),
      get_categories: require('./api/ml.get_categories.js')(opts),
      getCategories: require('./api/ml.get_categories.js')(opts),
      get_data_frame_analytics: require('./api/ml.get_data_frame_analytics.js')(opts),
      getDataFrameAnalytics: require('./api/ml.get_data_frame_analytics.js')(opts),
      get_data_frame_analytics_stats: require('./api/ml.get_data_frame_analytics_stats.js')(opts),
      getDataFrameAnalyticsStats: require('./api/ml.get_data_frame_analytics_stats.js')(opts),
      get_datafeed_stats: require('./api/ml.get_datafeed_stats.js')(opts),
      getDatafeedStats: require('./api/ml.get_datafeed_stats.js')(opts),
      get_datafeeds: require('./api/ml.get_datafeeds.js')(opts),
      getDatafeeds: require('./api/ml.get_datafeeds.js')(opts),
      get_filters: require('./api/ml.get_filters.js')(opts),
      getFilters: require('./api/ml.get_filters.js')(opts),
      get_influencers: require('./api/ml.get_influencers.js')(opts),
      getInfluencers: require('./api/ml.get_influencers.js')(opts),
      get_job_stats: require('./api/ml.get_job_stats.js')(opts),
      getJobStats: require('./api/ml.get_job_stats.js')(opts),
      get_jobs: require('./api/ml.get_jobs.js')(opts),
      getJobs: require('./api/ml.get_jobs.js')(opts),
      get_model_snapshots: require('./api/ml.get_model_snapshots.js')(opts),
      getModelSnapshots: require('./api/ml.get_model_snapshots.js')(opts),
      get_overall_buckets: require('./api/ml.get_overall_buckets.js')(opts),
      getOverallBuckets: require('./api/ml.get_overall_buckets.js')(opts),
      get_records: require('./api/ml.get_records.js')(opts),
      getRecords: require('./api/ml.get_records.js')(opts),
      get_trained_models: require('./api/ml.get_trained_models.js')(opts),
      getTrainedModels: require('./api/ml.get_trained_models.js')(opts),
      get_trained_models_stats: require('./api/ml.get_trained_models_stats.js')(opts),
      getTrainedModelsStats: require('./api/ml.get_trained_models_stats.js')(opts),
      info: require('./api/ml.info.js')(opts),
      open_job: require('./api/ml.open_job.js')(opts),
      openJob: require('./api/ml.open_job.js')(opts),
      post_calendar_events: require('./api/ml.post_calendar_events.js')(opts),
      postCalendarEvents: require('./api/ml.post_calendar_events.js')(opts),
      post_data: require('./api/ml.post_data.js')(opts),
      postData: require('./api/ml.post_data.js')(opts),
      preview_datafeed: require('./api/ml.preview_datafeed.js')(opts),
      previewDatafeed: require('./api/ml.preview_datafeed.js')(opts),
      put_calendar: require('./api/ml.put_calendar.js')(opts),
      putCalendar: require('./api/ml.put_calendar.js')(opts),
      put_calendar_job: require('./api/ml.put_calendar_job.js')(opts),
      putCalendarJob: require('./api/ml.put_calendar_job.js')(opts),
      put_data_frame_analytics: require('./api/ml.put_data_frame_analytics.js')(opts),
      putDataFrameAnalytics: require('./api/ml.put_data_frame_analytics.js')(opts),
      put_datafeed: require('./api/ml.put_datafeed.js')(opts),
      putDatafeed: require('./api/ml.put_datafeed.js')(opts),
      put_filter: require('./api/ml.put_filter.js')(opts),
      putFilter: require('./api/ml.put_filter.js')(opts),
      put_job: require('./api/ml.put_job.js')(opts),
      putJob: require('./api/ml.put_job.js')(opts),
      put_trained_model: require('./api/ml.put_trained_model.js')(opts),
      putTrainedModel: require('./api/ml.put_trained_model.js')(opts),
      revert_model_snapshot: require('./api/ml.revert_model_snapshot.js')(opts),
      revertModelSnapshot: require('./api/ml.revert_model_snapshot.js')(opts),
      set_upgrade_mode: require('./api/ml.set_upgrade_mode.js')(opts),
      setUpgradeMode: require('./api/ml.set_upgrade_mode.js')(opts),
      start_data_frame_analytics: require('./api/ml.start_data_frame_analytics.js')(opts),
      startDataFrameAnalytics: require('./api/ml.start_data_frame_analytics.js')(opts),
      start_datafeed: require('./api/ml.start_datafeed.js')(opts),
      startDatafeed: require('./api/ml.start_datafeed.js')(opts),
      stop_data_frame_analytics: require('./api/ml.stop_data_frame_analytics.js')(opts),
      stopDataFrameAnalytics: require('./api/ml.stop_data_frame_analytics.js')(opts),
      stop_datafeed: require('./api/ml.stop_datafeed.js')(opts),
      stopDatafeed: require('./api/ml.stop_datafeed.js')(opts),
      update_datafeed: require('./api/ml.update_datafeed.js')(opts),
      updateDatafeed: require('./api/ml.update_datafeed.js')(opts),
      update_filter: require('./api/ml.update_filter.js')(opts),
      updateFilter: require('./api/ml.update_filter.js')(opts),
      update_job: require('./api/ml.update_job.js')(opts),
      updateJob: require('./api/ml.update_job.js')(opts),
      update_model_snapshot: require('./api/ml.update_model_snapshot.js')(opts),
      updateModelSnapshot: require('./api/ml.update_model_snapshot.js')(opts),
      validate: require('./api/ml.validate.js')(opts),
      validate_detector: require('./api/ml.validate_detector.js')(opts),
      validateDetector: require('./api/ml.validate_detector.js')(opts)
    },
    monitoring: {
      bulk: require('./api/monitoring.bulk.js')(opts)
    },
    msearch: require('./api/msearch.js')(opts),
    msearch_template: require('./api/msearch_template.js')(opts),
    msearchTemplate: require('./api/msearch_template.js')(opts),
    mtermvectors: require('./api/mtermvectors.js')(opts),
    nodes: {
      hot_threads: require('./api/nodes.hot_threads.js')(opts),
      hotThreads: require('./api/nodes.hot_threads.js')(opts),
      info: require('./api/nodes.info.js')(opts),
      reload_secure_settings: require('./api/nodes.reload_secure_settings.js')(opts),
      reloadSecureSettings: require('./api/nodes.reload_secure_settings.js')(opts),
      stats: require('./api/nodes.stats.js')(opts),
      usage: require('./api/nodes.usage.js')(opts)
    },
    ping: require('./api/ping.js')(opts),
    put_script: require('./api/put_script.js')(opts),
    putScript: require('./api/put_script.js')(opts),
    rank_eval: require('./api/rank_eval.js')(opts),
    rankEval: require('./api/rank_eval.js')(opts),
    reindex: require('./api/reindex.js')(opts),
    reindex_rethrottle: require('./api/reindex_rethrottle.js')(opts),
    reindexRethrottle: require('./api/reindex_rethrottle.js')(opts),
    render_search_template: require('./api/render_search_template.js')(opts),
    renderSearchTemplate: require('./api/render_search_template.js')(opts),
    rollup: {
      delete_job: require('./api/rollup.delete_job.js')(opts),
      deleteJob: require('./api/rollup.delete_job.js')(opts),
      get_jobs: require('./api/rollup.get_jobs.js')(opts),
      getJobs: require('./api/rollup.get_jobs.js')(opts),
      get_rollup_caps: require('./api/rollup.get_rollup_caps.js')(opts),
      getRollupCaps: require('./api/rollup.get_rollup_caps.js')(opts),
      get_rollup_index_caps: require('./api/rollup.get_rollup_index_caps.js')(opts),
      getRollupIndexCaps: require('./api/rollup.get_rollup_index_caps.js')(opts),
      put_job: require('./api/rollup.put_job.js')(opts),
      putJob: require('./api/rollup.put_job.js')(opts),
      rollup_search: require('./api/rollup.rollup_search.js')(opts),
      rollupSearch: require('./api/rollup.rollup_search.js')(opts),
      start_job: require('./api/rollup.start_job.js')(opts),
      startJob: require('./api/rollup.start_job.js')(opts),
      stop_job: require('./api/rollup.stop_job.js')(opts),
      stopJob: require('./api/rollup.stop_job.js')(opts)
    },
    scripts_painless_execute: require('./api/scripts_painless_execute.js')(opts),
    scriptsPainlessExecute: require('./api/scripts_painless_execute.js')(opts),
    scroll: require('./api/scroll.js')(opts),
    search: require('./api/search.js')(opts),
    search_shards: require('./api/search_shards.js')(opts),
    searchShards: require('./api/search_shards.js')(opts),
    search_template: require('./api/search_template.js')(opts),
    searchTemplate: require('./api/search_template.js')(opts),
    security: {
      authenticate: require('./api/security.authenticate.js')(opts),
      change_password: require('./api/security.change_password.js')(opts),
      changePassword: require('./api/security.change_password.js')(opts),
      clear_cached_realms: require('./api/security.clear_cached_realms.js')(opts),
      clearCachedRealms: require('./api/security.clear_cached_realms.js')(opts),
      clear_cached_roles: require('./api/security.clear_cached_roles.js')(opts),
      clearCachedRoles: require('./api/security.clear_cached_roles.js')(opts),
      create_api_key: require('./api/security.create_api_key.js')(opts),
      createApiKey: require('./api/security.create_api_key.js')(opts),
      delete_privileges: require('./api/security.delete_privileges.js')(opts),
      deletePrivileges: require('./api/security.delete_privileges.js')(opts),
      delete_role: require('./api/security.delete_role.js')(opts),
      deleteRole: require('./api/security.delete_role.js')(opts),
      delete_role_mapping: require('./api/security.delete_role_mapping.js')(opts),
      deleteRoleMapping: require('./api/security.delete_role_mapping.js')(opts),
      delete_user: require('./api/security.delete_user.js')(opts),
      deleteUser: require('./api/security.delete_user.js')(opts),
      disable_user: require('./api/security.disable_user.js')(opts),
      disableUser: require('./api/security.disable_user.js')(opts),
      enable_user: require('./api/security.enable_user.js')(opts),
      enableUser: require('./api/security.enable_user.js')(opts),
      get_api_key: require('./api/security.get_api_key.js')(opts),
      getApiKey: require('./api/security.get_api_key.js')(opts),
      get_builtin_privileges: require('./api/security.get_builtin_privileges.js')(opts),
      getBuiltinPrivileges: require('./api/security.get_builtin_privileges.js')(opts),
      get_privileges: require('./api/security.get_privileges.js')(opts),
      getPrivileges: require('./api/security.get_privileges.js')(opts),
      get_role: require('./api/security.get_role.js')(opts),
      getRole: require('./api/security.get_role.js')(opts),
      get_role_mapping: require('./api/security.get_role_mapping.js')(opts),
      getRoleMapping: require('./api/security.get_role_mapping.js')(opts),
      get_token: require('./api/security.get_token.js')(opts),
      getToken: require('./api/security.get_token.js')(opts),
      get_user: require('./api/security.get_user.js')(opts),
      getUser: require('./api/security.get_user.js')(opts),
      get_user_privileges: require('./api/security.get_user_privileges.js')(opts),
      getUserPrivileges: require('./api/security.get_user_privileges.js')(opts),
      has_privileges: require('./api/security.has_privileges.js')(opts),
      hasPrivileges: require('./api/security.has_privileges.js')(opts),
      invalidate_api_key: require('./api/security.invalidate_api_key.js')(opts),
      invalidateApiKey: require('./api/security.invalidate_api_key.js')(opts),
      invalidate_token: require('./api/security.invalidate_token.js')(opts),
      invalidateToken: require('./api/security.invalidate_token.js')(opts),
      put_privileges: require('./api/security.put_privileges.js')(opts),
      putPrivileges: require('./api/security.put_privileges.js')(opts),
      put_role: require('./api/security.put_role.js')(opts),
      putRole: require('./api/security.put_role.js')(opts),
      put_role_mapping: require('./api/security.put_role_mapping.js')(opts),
      putRoleMapping: require('./api/security.put_role_mapping.js')(opts),
      put_user: require('./api/security.put_user.js')(opts),
      putUser: require('./api/security.put_user.js')(opts)
    },
    slm: {
      delete_lifecycle: require('./api/slm.delete_lifecycle.js')(opts),
      deleteLifecycle: require('./api/slm.delete_lifecycle.js')(opts),
      execute_lifecycle: require('./api/slm.execute_lifecycle.js')(opts),
      executeLifecycle: require('./api/slm.execute_lifecycle.js')(opts),
      execute_retention: require('./api/slm.execute_retention.js')(opts),
      executeRetention: require('./api/slm.execute_retention.js')(opts),
      get_lifecycle: require('./api/slm.get_lifecycle.js')(opts),
      getLifecycle: require('./api/slm.get_lifecycle.js')(opts),
      get_stats: require('./api/slm.get_stats.js')(opts),
      getStats: require('./api/slm.get_stats.js')(opts),
      get_status: require('./api/slm.get_status.js')(opts),
      getStatus: require('./api/slm.get_status.js')(opts),
      put_lifecycle: require('./api/slm.put_lifecycle.js')(opts),
      putLifecycle: require('./api/slm.put_lifecycle.js')(opts),
      start: require('./api/slm.start.js')(opts),
      stop: require('./api/slm.stop.js')(opts)
    },
    snapshot: {
      cleanup_repository: require('./api/snapshot.cleanup_repository.js')(opts),
      cleanupRepository: require('./api/snapshot.cleanup_repository.js')(opts),
      create: require('./api/snapshot.create.js')(opts),
      create_repository: require('./api/snapshot.create_repository.js')(opts),
      createRepository: require('./api/snapshot.create_repository.js')(opts),
      delete: require('./api/snapshot.delete.js')(opts),
      delete_repository: require('./api/snapshot.delete_repository.js')(opts),
      deleteRepository: require('./api/snapshot.delete_repository.js')(opts),
      get: require('./api/snapshot.get.js')(opts),
      get_repository: require('./api/snapshot.get_repository.js')(opts),
      getRepository: require('./api/snapshot.get_repository.js')(opts),
      restore: require('./api/snapshot.restore.js')(opts),
      status: require('./api/snapshot.status.js')(opts),
      verify_repository: require('./api/snapshot.verify_repository.js')(opts),
      verifyRepository: require('./api/snapshot.verify_repository.js')(opts)
    },
    sql: {
      clear_cursor: require('./api/sql.clear_cursor.js')(opts),
      clearCursor: require('./api/sql.clear_cursor.js')(opts),
      query: require('./api/sql.query.js')(opts),
      translate: require('./api/sql.translate.js')(opts)
    },
    ssl: {
      certificates: require('./api/ssl.certificates.js')(opts)
    },
    tasks: {
      cancel: require('./api/tasks.cancel.js')(opts),
      get: require('./api/tasks.get.js')(opts),
      list: require('./api/tasks.list.js')(opts)
    },
    termvectors: require('./api/termvectors.js')(opts),
    transform: {
      delete_transform: require('./api/transform.delete_transform.js')(opts),
      deleteTransform: require('./api/transform.delete_transform.js')(opts),
      get_transform: require('./api/transform.get_transform.js')(opts),
      getTransform: require('./api/transform.get_transform.js')(opts),
      get_transform_stats: require('./api/transform.get_transform_stats.js')(opts),
      getTransformStats: require('./api/transform.get_transform_stats.js')(opts),
      preview_transform: require('./api/transform.preview_transform.js')(opts),
      previewTransform: require('./api/transform.preview_transform.js')(opts),
      put_transform: require('./api/transform.put_transform.js')(opts),
      putTransform: require('./api/transform.put_transform.js')(opts),
      start_transform: require('./api/transform.start_transform.js')(opts),
      startTransform: require('./api/transform.start_transform.js')(opts),
      stop_transform: require('./api/transform.stop_transform.js')(opts),
      stopTransform: require('./api/transform.stop_transform.js')(opts),
      update_transform: require('./api/transform.update_transform.js')(opts),
      updateTransform: require('./api/transform.update_transform.js')(opts)
    },
    update: require('./api/update.js')(opts),
    update_by_query: require('./api/update_by_query.js')(opts),
    updateByQuery: require('./api/update_by_query.js')(opts),
    update_by_query_rethrottle: require('./api/update_by_query_rethrottle.js')(opts),
    updateByQueryRethrottle: require('./api/update_by_query_rethrottle.js')(opts),
    watcher: {
      ack_watch: require('./api/watcher.ack_watch.js')(opts),
      ackWatch: require('./api/watcher.ack_watch.js')(opts),
      activate_watch: require('./api/watcher.activate_watch.js')(opts),
      activateWatch: require('./api/watcher.activate_watch.js')(opts),
      deactivate_watch: require('./api/watcher.deactivate_watch.js')(opts),
      deactivateWatch: require('./api/watcher.deactivate_watch.js')(opts),
      delete_watch: require('./api/watcher.delete_watch.js')(opts),
      deleteWatch: require('./api/watcher.delete_watch.js')(opts),
      execute_watch: require('./api/watcher.execute_watch.js')(opts),
      executeWatch: require('./api/watcher.execute_watch.js')(opts),
      get_watch: require('./api/watcher.get_watch.js')(opts),
      getWatch: require('./api/watcher.get_watch.js')(opts),
      put_watch: require('./api/watcher.put_watch.js')(opts),
      putWatch: require('./api/watcher.put_watch.js')(opts),
      start: require('./api/watcher.start.js')(opts),
      stats: require('./api/watcher.stats.js')(opts),
      stop: require('./api/watcher.stop.js')(opts)
    },
    xpack: {
      info: require('./api/xpack.info.js')(opts),
      usage: require('./api/xpack.usage.js')(opts)
    }
  }

  return apis

  function handleError (err, callback) {
    if (callback) return callback(err, result)
    return Promise.reject(err)
  }

  function snakeCaseKeys (acceptedQuerystring, snakeCase, querystring, warnings) {
    var target = {}
    var keys = Object.keys(querystring)
    for (var i = 0, len = keys.length; i < len; i++) {
      var key = keys[i]
      target[snakeCase[key] || key] = querystring[key]
      if (acceptedQuerystring.indexOf(snakeCase[key] || key) === -1) {
        warnings.push('Client - Unknown parameter: "' + key + '", sending it as query parameter')
      }
    }
    return target
  }
}

module.exports = ESAPI
